// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB22htgK6qZac-86xgve6t3lUWS6uMPLOg',
    appId: '1:707722927533:web:207b432c2d17664d689524',
    messagingSenderId: '707722927533',
    projectId: 'abdayex2',
    authDomain: 'abdayex2.firebaseapp.com',
    storageBucket: 'abdayex2.appspot.com',
    measurementId: 'G-0CR63PMWHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnjRXaHzfEgaiqBLcUmidXd49IoqVatjU',
    appId: '1:707722927533:android:d3556b4d8a34766a689524',
    messagingSenderId: '707722927533',
    projectId: 'abdayex2',
    storageBucket: 'abdayex2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCogi9DvoUTEteq9wShO6r6-8tPfUQO89I',
    appId: '1:707722927533:ios:287b0aca10392450689524',
    messagingSenderId: '707722927533',
    projectId: 'abdayex2',
    storageBucket: 'abdayex2.appspot.com',
    iosBundleId: 'com.example.ipeApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCogi9DvoUTEteq9wShO6r6-8tPfUQO89I',
    appId: '1:707722927533:ios:47cbef476b5e6842689524',
    messagingSenderId: '707722927533',
    projectId: 'abdayex2',
    storageBucket: 'abdayex2.appspot.com',
    iosBundleId: 'com.example.ipeApplication.RunnerTests',
  );
}
